# Generated by Django 3.2 on 2021-05-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Hello, World!', max_length=50)),
                ('description', models.TextField(default='Welcome to the world of programming!')),
            ],
        ),
    ]
